version: "3.8"

services:

  langgraph:
    build: ./langgraph
    image: langchain-stack_langgraph:latest
    restart: unless-stopped
    env_file: .env
    ports:
      # bind container’s 8000 to host’s 127.0.0.1:8000 (IPv4 only)
      - "127.0.0.1:8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: uvicorn server:app --host 0.0.0.0 --port 8000

  studio:
    build: ./studio
    image: langchain-stack_studio:latest
    restart: unless-stopped
    depends_on:
      - langgraph
    env_file: .env
    environment:
      - REACT_APP_API_URL=http://langgraph:8000
    ports:
      # expose UI’s port 80 on host port 3000 (all interfaces)
      - "3000:80"
